name: whiteboard_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  country_code_picker: ^3.0.0 #^2.0.2
  change_app_package_name: ^1.0.0
  firebase_core: ^2.3.0 #^1.10.5
  cloud_firestore: ^4.1.0 #^3.1.11
  firebase_auth: 4.1.5 #^3.3.3
  provider: ^6.0.1
  uuid: ^3.0.5
  image_picker: ^0.8.4+4 #Add for IOS
  firebase_storage: ^11.0.6 #^10.2.4
  camera: ^0.10.5+3
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4 #^2.1.0
  firebase_messaging: ^14.1.3 #^11.4.2 #^11.2.4
  flutter_callkit_incoming: ^1.0.2+2 #^1.0.2+2
  simple_ripple_animation: ^0.0.3
  like_button: ^2.0.4
  stop_watch_timer: ^2.0.0 #^1.3.1
  connectivity_plus: ^2.2.0
  cloud_functions: ^4.0.5 #^3.2.17 #^3.2.10
  substring_highlight: ^1.0.33
  adaptive_scrollbar: ^2.1.2
  diacritic: ^0.1.3
  flutter_stripe: ^7.0.0 #^3.0.2 # IOS 11 minimum
  dropdown_button2: ^1.5.0
  flutter_local_notifications: ^15.1.1
  url_launcher: ^6.1.0 #Add for IOS + ANDROID if "canLaunchUrl" is used
  eraser: ^2.0.1
  shared_preferences: ^2.0.15
  file_picker: ^5.0.0
  upgrader: ^4.6.1
  circular_countdown_timer: ^0.2.3
  permission_handler: ^11.0.0 #^10.2.0
  phosphor_flutter: ^1.4.0
  flutter_webrtc: ^0.9.24
  sdp_transform: ^0.3.2
  gallery_saver: ^2.3.2
  flutter_isolate: ^2.0.4
  flutter_foreground_task: ^6.0.0+1
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  video_player: ^2.7.0
  flutter_image_compress: ^2.0.4
  draggable_widget: ^2.0.0
  square_percent_indicater: ^0.1.0
  public_ip_address: ^1.0.0
  intl: ^0.18.1
  pod_player: any
  rainbow_color: ^2.0.1
  volume_controller: ^2.0.7 #Delete from here

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
